# Generated by Django 4.1.2 on 2022-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
