# Generated by Django 4.1.2 on 2022-11-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0002_jmuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='track',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='track',
            name='index',
        ),
        migrations.RemoveField(
            model_name='track',
            name='name',
        ),
        migrations.AddField(
            model_name='track',
            name='uri',
            field=models.CharField(default='null', max_length=512),
            preserve_default=False,
        ),
    ]
