# Generated by Django 4.1.2 on 2022-11-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0003_remove_track_album_remove_track_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jmuser',
            old_name='top_songs',
            new_name='top_tracks',
        ),
    ]
