# Generated by Django 4.1.2 on 2022-11-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0005_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmuser',
            name='about',
            field=models.CharField(default='aaaa', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jmuser',
            name='vibes',
            field=models.CharField(default='aaaaaa', max_length=256),
            preserve_default=False,
        ),
    ]
