# Generated by Django 4.1.2 on 2022-11-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0006_jmuser_about_jmuser_vibes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmuser',
            name='music_taste',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
