# Generated by Django 4.1.1 on 2022-11-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0007_jmuser_music_taste'),
        ('judgeme', '0007_track_picture'),
    ]

    operations = [
    ]
