# Generated by Django 4.1.2 on 2022-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0008_merge_0007_jmuser_music_taste_0007_track_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmuser',
            name='playlist_count',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
