# Generated by Django 4.1.2 on 2022-11-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0008_merge_0007_jmuser_music_taste_0007_track_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmuser',
            name='music_taste',
            field=models.FloatField(default=-1),
        ),
    ]
