# Generated by Django 4.1.1 on 2022-11-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0009_jmuser_playlist_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmuser',
            name='music_taste',
            field=models.FloatField(default=-1),
        ),
    ]
