# Generated by Django 4.1.2 on 2022-11-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0009_alter_jmuser_music_taste'),
        ('judgeme', '0010_alter_jmuser_music_taste'),
    ]

    operations = [
    ]
