# Generated by Django 4.1.2 on 2022-11-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0012_remove_artist_location_artist_picture_artist_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='top_genre',
            field=models.CharField(default='hyperpop', max_length=256),
            preserve_default=False,
        ),
    ]
