# Generated by Django 4.1.2 on 2022-11-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0013_artist_top_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmuser',
            name='display_name',
            field=models.CharField(default='display_name placeholder', max_length=256),
            preserve_default=False,
        ),
    ]
