# Generated by Django 4.1.2 on 2022-11-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0015_track_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_preview',
            field=models.CharField(default='audio_preview_placeholder', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='uri',
            field=models.CharField(max_length=256),
        ),
    ]
