# Generated by Django 4.1.1 on 2022-11-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0016_track_audio_preview_alter_track_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmuser',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
