# Generated by Django 4.1.1 on 2022-12-01 02:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0016_track_audio_preview_alter_track_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmuser',
            name='music_taste',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0, 0, 0, 0, 0], size=5),
        ),
    ]
