# Generated by Django 4.1.1 on 2022-11-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0017_jmuser_uploaded_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=256)),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
