# Generated by Django 4.1.1 on 2022-12-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0018_alter_jmuser_music_taste'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmuser',
            name='agreeableness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jmuser',
            name='conscientiousness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jmuser',
            name='emotional_stability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jmuser',
            name='extravertedness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jmuser',
            name='openness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jmuser',
            name='music_taste',
            field=models.FloatField(default=-1),
        ),
    ]
