# Generated by Django 4.1.1 on 2022-11-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0018_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
