# Generated by Django 4.1.1 on 2022-11-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0019_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
    ]
