# Generated by Django 4.1.1 on 2022-12-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0019_jmuser_agreeableness_jmuser_conscientiousness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('uri', models.CharField(max_length=512)),
                ('playlist_pic', models.CharField(max_length=256)),
                ('tracks', models.ManyToManyField(blank=True, to='judgeme.track')),
            ],
        ),
        migrations.AddField(
            model_name='jmuser',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='judgeme.playlist'),
        ),
    ]
