# Generated by Django 4.1.1 on 2022-11-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0020_remove_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmuser',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
        migrations.AlterField(
            model_name='test',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
    ]
