# Generated by Django 4.1.1 on 2022-12-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0020_playlist_jmuser_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_music_taste',
            field=models.FloatField(default=-1),
        ),
    ]
