# Generated by Django 4.1.2 on 2022-12-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0021_playlist_playlist_music_taste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(to='judgeme.track'),
        ),
        migrations.AddField(
            model_name='jmuser',
            name='top_track_name',
            field=models.CharField(default='top_track_name placeholder', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgeme.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jmuser',
            name='music_taste',
            field=models.IntegerField(default=-1),
        ),
    ]
