# Generated by Django 4.1.1 on 2022-11-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0022_alter_test_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='username',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
