# Generated by Django 4.1.1 on 2022-11-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0023_image_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
