# Generated by Django 4.1.1 on 2022-11-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0024_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
    ]
