# Generated by Django 4.1.1 on 2022-12-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0027_alter_jmuser_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmuser',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
    ]
